"""Spectral-mode matrix toy for Muon-family optimizer screening.

The toy has a known spectral basis U0, V0.  The loss is quadratic in
Z = U0^T W V0, with diagonal target modes and a small off-diagonal penalty.
Two microbatch gradients are generated by adding independent full-rank noise.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List, Sequence, Tuple

import numpy as np

from .linalg_utils import EPS
from .optimizers import make_update


@dataclass(frozen=True)
class ToyConfig:
    setting: str = "mixed"
    n: int = 32
    steps: int = 200
    lr: float = 0.05
    momentum: float = 0.9
    noise: float = 0.03
    offdiag_curv: float = 0.05
    seed: int = 0
    kappa_mode: str = "true"  # true | ones
    rt_delta: float = 0.35
    rt_lambda_nu: float = 2.0
    rt_lambda_c: float = 0.25
    sq_lambda_diff: float = 0.5
    sq_lambda_uncert: float = 0.5
    sq_lambda_tube: float = 0.05
    sq_phi_threshold: float = 0.0
    sq_soft_tau: float = 0.001
    sq_quench_mode: str = "hard"
    sq_diffusion_mode: str = "mean"
    beta_grid: Tuple[float, ...] = (0.0, 0.001, 0.002, 0.005, 0.01, 0.02, 0.05, 0.1, 0.25, 0.5, 1.0, 2.0, 4.0)


def random_orthogonal(rng: np.random.Generator, n: int) -> np.ndarray:
    a = rng.normal(size=(n, n))
    q, r = np.linalg.qr(a)
    signs = np.sign(np.diag(r))
    signs[signs == 0] = 1.0
    return q * signs


def make_spectrum(setting: str, n: int) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Return target diag, curvature diag, strong_idx, weak_idx."""
    idx = np.arange(n)
    curv = np.geomspace(1.0, 0.05, n)
    target = np.zeros(n)

    if setting == "fullrank":
        target[:] = 1.0
        strong = idx[: max(4, n // 4)]
        weak = idx[-max(4, n // 4):]
    elif setting == "lowrank":
        k = max(4, n // 8)
        target[:k] = 1.0
        strong = idx[:k]
        weak = np.array([], dtype=int)
    elif setting == "mixed":
        k_strong = max(4, n // 8)
        k_weak = max(4, n // 8)
        target[:k_strong] = 1.0
        target[k_strong:k_strong + k_weak] = 0.20
        strong = idx[:k_strong]
        weak = idx[k_strong:k_strong + k_weak]
    elif setting == "spiked_noise":
        k_strong = max(4, n // 8)
        k_weak = max(6, n // 5)
        target[:k_strong] = 1.0
        target[k_strong:k_strong + k_weak] = 0.15
        strong = idx[:k_strong]
        weak = idx[k_strong:k_strong + k_weak]
    else:
        raise ValueError(f"Unknown setting: {setting}")

    return target, curv, strong, weak


class SpectralToy:
    def __init__(self, cfg: ToyConfig):
        self.cfg = cfg
        self.rng = np.random.default_rng(cfg.seed)
        self.n = cfg.n
        self.U0 = random_orthogonal(self.rng, self.n)
        self.V0 = random_orthogonal(self.rng, self.n)
        self.target, self.curv, self.strong_idx, self.weak_idx = make_spectrum(cfg.setting, self.n)
        self.tail_idx = np.where(np.abs(self.target) < 1e-12)[0]

    def z_of(self, W: np.ndarray) -> np.ndarray:
        return self.U0.T @ W @ self.V0

    def loss_and_grad(self, W: np.ndarray) -> Tuple[float, np.ndarray, Dict[str, float]]:
        Z = self.z_of(W)
        diag = np.diag(Z)
        diag_err = diag - self.target
        off = Z.copy()
        np.fill_diagonal(off, 0.0)
        loss_diag = 0.5 * float(np.sum(self.curv * diag_err * diag_err))
        loss_off = 0.5 * float(self.cfg.offdiag_curv * np.sum(off * off))
        grad_Z = self.cfg.offdiag_curv * off
        np.fill_diagonal(grad_Z, self.curv * diag_err)
        G = self.U0 @ grad_Z @ self.V0.T
        weak_err = float(np.mean(diag_err[self.weak_idx] ** 2)) if self.weak_idx.size else float("nan")
        strong_err = float(np.mean(diag_err[self.strong_idx] ** 2)) if self.strong_idx.size else float("nan")
        tail_err = float(np.mean(diag[self.tail_idx] ** 2)) if self.tail_idx.size else float("nan")
        return loss_diag + loss_off, G, {"weak_error": weak_err, "strong_error": strong_err, "tail_param_error": tail_err}

    def noise_matrix(self) -> np.ndarray:
        n = self.n
        z = self.rng.normal(size=(n, n)) / np.sqrt(n)
        if self.cfg.setting == "spiked_noise":
            u = self.rng.normal(size=n); u /= np.linalg.norm(u) + EPS
            v = self.rng.normal(size=n); v /= np.linalg.norm(v) + EPS
            z = z + 2.0 * np.outer(u, v) * self.rng.normal()
        return self.cfg.noise * z

    def tail_update_mass(self, Q: np.ndarray) -> float:
        Zq = self.z_of(Q)
        diag_q = np.diag(Zq)
        denom = float(np.sum(Zq * Zq)) + EPS
        if self.tail_idx.size == 0:
            return float("nan")
        return float(np.sum(diag_q[self.tail_idx] ** 2) / denom)


def simulate_one(method: str, cfg: ToyConfig) -> Dict[str, float | str | int]:
    toy = SpectralToy(cfg)
    n = cfg.n
    W = np.zeros((n, n), dtype=float)
    M = np.zeros_like(W)
    target_fro = np.sqrt(min(W.shape))
    kappa = toy.curv if cfg.kappa_mode == "true" else np.ones(n)

    losses: List[float] = []
    weak_errors: List[float] = []
    tail_errors: List[float] = []
    tail_masses: List[float] = []
    entropies: List[float] = []
    pmaxes: List[float] = []
    betas: List[float] = []
    beta_candidates: List[float] = []
    soft_shrinks: List[float] = []
    cv_gains: List[float] = []
    raw_gains: List[float] = []
    phis: List[float] = []
    diff_costs: List[float] = []
    uncert_costs: List[float] = []
    tube_penalties: List[float] = []
    fro_ratios: List[float] = []
    mean_abs_w: List[float] = []
    min_ws: List[float] = []
    max_ws: List[float] = []

    initial_loss, _, _ = toy.loss_and_grad(W)

    for _ in range(cfg.steps):
        _, G_true, _ = toy.loss_and_grad(W)
        Ga = G_true + toy.noise_matrix()
        Gb = G_true + toy.noise_matrix()
        Gbar = 0.5 * (Ga + Gb)
        M = cfg.momentum * M + Gbar

        Q, info = make_update(
            method, M, Ga, Gb, target_fro=target_fro, eta=cfg.lr,
            kappa_diag=kappa, beta_grid=cfg.beta_grid,
            rt_delta=cfg.rt_delta, rt_lambda_nu=cfg.rt_lambda_nu, rt_lambda_c=cfg.rt_lambda_c,
            sq_lambda_diff=cfg.sq_lambda_diff, sq_lambda_uncert=cfg.sq_lambda_uncert,
            sq_lambda_tube=cfg.sq_lambda_tube, sq_phi_threshold=cfg.sq_phi_threshold,
            sq_soft_tau=cfg.sq_soft_tau, sq_quench_mode=cfg.sq_quench_mode,
            sq_diffusion_mode=cfg.sq_diffusion_mode,
        )
        W = W - cfg.lr * Q

        new_loss, _, new_parts = toy.loss_and_grad(W)
        losses.append(new_loss)
        weak_errors.append(new_parts["weak_error"])
        tail_errors.append(new_parts["tail_param_error"])
        tail_masses.append(toy.tail_update_mass(Q))
        entropies.append(info.entropy)
        pmaxes.append(info.pmax)
        betas.append(info.beta_star)
        beta_candidates.append(info.beta_candidate)
        soft_shrinks.append(info.soft_shrink)
        cv_gains.append(info.cv_gain)
        raw_gains.append(info.raw_cv_gain)
        phis.append(info.phi)
        diff_costs.append(info.diffusion_cost)
        uncert_costs.append(info.uncertainty_cost)
        tube_penalties.append(info.tube_penalty)
        fro_ratios.append(info.update_fro / (target_fro + EPS))
        mean_abs_w.append(info.mean_abs_w_minus_1)
        min_ws.append(info.min_w)
        max_ws.append(info.max_w)

    def nanmean(x: Sequence[float]) -> float:
        arr = np.asarray(x, dtype=float)
        if arr.size == 0 or np.all(np.isnan(arr)):
            return float("nan")
        return float(np.nanmean(arr))

    def auc(x: Sequence[float]) -> float:
        arr = np.asarray(x, dtype=float)
        if arr.size == 0 or np.all(np.isnan(arr)):
            return float("nan")
        return float(np.nanmean(arr))

    final_loss = float(losses[-1]) if losses else float(initial_loss)
    rec: Dict[str, float | str | int] = {
        "method": method,
        "setting": cfg.setting,
        "seed": cfg.seed,
        "lr": cfg.lr,
        "steps": cfg.steps,
        "n": cfg.n,
        "noise": cfg.noise,
        "momentum": cfg.momentum,
        "rt_delta": cfg.rt_delta,
        "rt_lambda_nu": cfg.rt_lambda_nu,
        "rt_lambda_c": cfg.rt_lambda_c,
        "sq_lambda_diff": cfg.sq_lambda_diff,
        "sq_lambda_uncert": cfg.sq_lambda_uncert,
        "sq_lambda_tube": cfg.sq_lambda_tube,
        "sq_phi_threshold": cfg.sq_phi_threshold,
        "sq_soft_tau": cfg.sq_soft_tau,
        "sq_quench_mode": cfg.sq_quench_mode,
        "sq_diffusion_mode": cfg.sq_diffusion_mode,
        "kappa_mode": cfg.kappa_mode,
        "initial_loss": float(initial_loss),
        "final_loss": final_loss,
        "auc_loss": auc(losses),
        "auc_weak_error": auc(weak_errors),
        "auc_tail_param_error": auc(tail_errors),
        "mean_tail_update_mass": nanmean(tail_masses),
        "mean_entropy": nanmean(entropies),
        "mean_pmax": nanmean(pmaxes),
        "mean_beta": nanmean(betas),
        "mean_beta_candidate": nanmean(beta_candidates),
        "mean_soft_shrink": nanmean(soft_shrinks),
        "beta_zero_rate": float(np.mean(np.asarray(betas) <= 0.0)) if betas else 1.0,
        "accept_rate": float(np.mean(np.asarray(betas) > 0.0)) if betas else 0.0,
        "mean_cv_gain": nanmean(cv_gains),
        "mean_raw_cv_gain": nanmean(raw_gains),
        "mean_phi": nanmean(phis),
        "mean_diffusion_cost": nanmean(diff_costs),
        "mean_uncertainty_cost": nanmean(uncert_costs),
        "mean_tube_penalty": nanmean(tube_penalties),
        "mean_fro_ratio": nanmean(fro_ratios),
        "mean_abs_w_minus_1": nanmean(mean_abs_w),
        "mean_min_w": nanmean(min_ws),
        "mean_max_w": nanmean(max_ws),
        "weak_modes": int(toy.weak_idx.size),
        "tail_modes": int(toy.tail_idx.size),
    }
    return rec
